forge "http://forge.puppetlabs.com"

mod "richardc/datacat", "0.5.0"
mod "puppetlabs/concat"
mod "puppetlabs/stdlib"
mod "puppetlabs/mysql"
mod "puppetlabs/haproxy" 
mod "puppetlabs/ntp"
mod "puppetlabs/apache"
mod "puppetlabs/mcollective"
mod "nanliu/staging"
mod "puppetlabs/apt"
mod "garethr/erlang"
mod "puppetlabs/rabbitmq"
mod "adrien/boolean"
mod "adrien/filemapper"
mod "adrien/network"
