forge "http://forge.puppetlabs.com"

mod "richardc/datacat"
mod "puppetlabs/concat"
mod "puppetlabs/stdlib"
mod "puppetlabs/mysql"
mod "puppetlabs/haproxy" 
mod "puppetlabs/ntp"
mod "puppetlabs/apache"
mod "puppetlabs/mcollective"
